# action.yml
name: 'download file'
description: 'download file to qbee file manager'
inputs:
  token:
    description: 'jwt token'
    required: true
  filename:
    description: 'tarname'
    required: true
    default: 'node-red-files.tar'
  qbee_directory:
    description: 'dirname'
    required: true
    default: 'qbee_github_action_test'
  local_directory:
    description: 'this directory contains path to the file which should be upload'
    required: true
    default: 'tar'
outputs:
  token:
    description: 'jwt token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.filename }}
    - ${{ inputs.qbee_directory }}
    - ${{ inputs.local_directory }}
